import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { db } from '@/lib/db';

function getDemoStoryline(topic: string, format: string, duration: string): string {
  return `# YouTube Video Script: ${topic}

## 1. Video Title
**"${topic}: Everything You Need to Know in ${duration}"**

---

## 2. Hook (0:00-0:30)
🎬 **VISUAL:** Dynamic montage with fast cuts, dramatic music building up

**SCRIPT:** "What if I told you that ${topic} is about to change everything you thought you knew? Stay tuned."

---

## 3. Introduction (0:30-1:00)
🎬 **VISUAL:** Host on camera, clean background

**SCRIPT:** "Hey everyone! Today we're diving deep into ${topic}. This ${format}-style video will give you a comprehensive overview. Let's get into it!"

---

## 4. Main Content Sections

### Section 1: What is ${topic}? (1:00-3:00)
**SCRIPT:** "Let's start with the basics. ${topic} refers to... Think of it like... Here's why this matters today."

### Section 2: How ${topic} Works (3:00-5:00)
**SCRIPT:** "Now let's look under the hood. ${topic} works through... Here's a practical example..."

### Section 3: Real-World Applications (5:00-7:00)
**SCRIPT:** "Where is ${topic} actually being used? Let me show you some incredible examples..."

### Section 4: The Future of ${topic} (7:00-8:30)
**SCRIPT:** "What does the future hold? Experts predict..."

---

## 5. Thumbnail Concept
Eye-catching split-screen design with bold text "${topic}: EXPLAINED", bright contrasting colors (orange/blue).

---

## 6. Tags/Keywords
**Primary:** ${topic}, ${topic} explained, ${topic} tutorial
**Hashtags:** #${topic.replace(/\s+/g, '')} #Tutorial #Education

---
*Script designed for ${format} format, target duration: ${duration}.*
*Generated by AI Video Storyline Generator - Demo Mode*`;
}

export async function POST(request: NextRequest) {
  try {
    const { topic, format, duration, researchData, workflowId } = await request.json();
    if (!topic) return NextResponse.json({ success: false, error: 'Topic is required' }, { status: 400 });

    let storyline: string;
    let isDemo = false;

    try {
      const client = new Anthropic();

      let researchContext = '';
      if (researchData?.trending?.length > 0) {
        researchContext = `\n\nTrending context:\n${researchData.trending.slice(0, 3).map((r: { name: string; snippet: string }) =>
          `- ${r.name}: ${r.snippet}`
        ).join('\n')}`;
      }

      const message = await client.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4096,
        system: `You are an expert YouTube content creator and scriptwriter. Create engaging, well-structured video content that captures audience attention and drives engagement. Your scripts are professional, include timing cues, visual suggestions, and are optimized for YouTube's algorithm.`,
        messages: [{
          role: 'user',
          content: `Create a comprehensive YouTube video storyline/script for:

Topic: ${topic}
Format: ${format || 'documentary'}
Target Duration: ${duration || '5-10 minutes'}
${researchContext}

Please provide:
1. **Video Title** - Catchy, SEO-optimized title
2. **Hook (0:00-0:30)** - Attention-grabbing opening
3. **Introduction (0:30-1:00)** - Brief overview
4. **Main Content Sections** - 3-5 key sections with timestamps
5. **Visual Cues** - Suggestions for B-roll, graphics
6. **Call to Action** - Engagement prompts
7. **Thumbnail Concept** - Description for an eye-catching thumbnail
8. **Tags/Keywords** - Relevant hashtags and keywords

Format the response in clear Markdown with proper headings.`
        }]
      });

      storyline = message.content[0].type === 'text' ? message.content[0].text : getDemoStoryline(topic, format || 'documentary', duration || '5-10 minutes');
    } catch (apiError: unknown) {
      const msg = apiError instanceof Error ? apiError.message : String(apiError);
      if (msg.includes('429') || msg.includes('rate limit') || msg.includes('overloaded')) {
        storyline = getDemoStoryline(topic, format || 'documentary', duration || '5-10 minutes');
        isDemo = true;
      } else {
        throw apiError;
      }
    }

    // Persist to workflow
    if (workflowId) {
      await db.workflow.update({
        where: { id: workflowId },
        data: { storyline, updatedAt: new Date() },
      }).catch(() => {});
    }

    return NextResponse.json({ success: true, storyline, topic, format, duration, isDemo });
  } catch (error) {
    console.error('Storyline generation error:', error);
    return NextResponse.json({ success: false, error: 'Failed to generate storyline' }, { status: 500 });
  }
}
